### ISSUE TITLE
[Question] Multithreading

### ISSUE THREAD

**Issue by isacikgoz** [sahilm/fuzzy#13]
Hello @sahilm

Do you consider improving performance with multi-threaded implementation? If so, I did this -> https://github.com/isacikgoz/fuzzy/commit/fc2d185b8ab5c12fcc68a446f904cae18fba066d if you approve it I can send a PR. 

Thanks in advance.

**Comment by sahilm** [comment]
Hey - Interesting idea however I cannot merge this because there is no way for our library to know when concurrency is appropriate and provides a speedup. If you run `make test` on the multi-threaded code you will see that it's in fact **slower** than the single-threaded version for the test datasets.

There might be cases where multi-threading will make things faster but that decision is better left to application authors to make. They can thread calls to `fuzzy.Find` as they see fit.

Thanks!
